/**
 * SchemaByte.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package com.altova.xml.types;

class SchemaByte implements SchemaType {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private byte value;

	private SchemaByte(int newvalue) {
		value = (byte)newvalue;
	}

	public int hashCode() {
		return value;
	}

	public boolean equals(Object obj) {
		if (!(obj instanceof SchemaByte))
			return false;
		return value == ((SchemaByte)obj).value;
	}

	public Object clone() {
		return new SchemaByte(value);
	}

	public String toString() {
		return Byte.toString(value);
	}

	public String asString() {
		return toString();
	}

	public int compareTo(Object obj) {
		return compareTo((SchemaByte)obj);
	}

	private int compareTo(SchemaByte obj) {
		return new Byte(value).compareTo(new Byte(obj.value));
	}
}
