/**
 * SchemaToken.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package com.altova.xml.types;

public class SchemaToken extends SchemaNormalizedString {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public SchemaToken(String newvalue) {
		super(newvalue);
	}

	public SchemaToken(SchemaToken newvalue) {
		super((SchemaNormalizedString)newvalue);
	}
}
