/**
 * SchemaLong.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package com.altova.xml.types;

class SchemaLong implements SchemaType {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long value;

	private SchemaLong(long newvalue) {
		value = newvalue;
	}

	public int hashCode() {
		return (int)value;
	}

	public boolean equals(Object obj) {
		if (!(obj instanceof SchemaLong))
			return false;
		return value == ((SchemaLong)obj).value;
	}

	public Object clone() {
		return new SchemaLong(value);
	}

	public String toString() {
		return Long.toString(value);
	}

	public String asString() {
		return toString();
	}

	public int compareTo(Object obj) {
		return compareTo((SchemaLong)obj);
	}

	private int compareTo(SchemaLong obj) {
		return new Long(value).compareTo(new Long(obj.value));
	}
}
