/**
 * XmlException.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.altova.xml;


public class XmlException extends RuntimeException {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String				message;

	public XmlException(String text) {
		message = text;
	}

	public XmlException(java.lang.Exception other) {
		message = other.getMessage();
	}

	public String getMessage() {
		return message;
	}
}
