/**
 * pmifschemaTest.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package pack.model.schema;

public class pmifschemaTest {
	protected static void example() throws Exception {
		////////////////////////////////////////////////////////////////////
		//
		//   Insert your code here...
		//
		// Example code to create and save a structure:
		//   pmifschemaDoc doc = new pmifschemaDoc();
		//   QNMType root = new QNMType();
		//   ...
		//   doc.setRootElementName("", "QueueingNetworkModel");
		//   doc.setSchemaLocation("pmifschema.xsd"); // optional
		//   doc.save("pmifschema1.xml", root);
		//
		// Example code to load and save a structure:
		//   pmifschemaDoc doc = new pmifschemaDoc();
		//   QNMType root = new QNMType(doc.load("pmifschema1.xml"));
		//   ...
		//   doc.save("pmifschema1.xml", root);
		//
		////////////////////////////////////////////////////////////////////
	}

	public static void main(String args[]) {
		try {
			System.out.println("pmifschema Test Application");
			example();
			System.out.println("OK");
			System.exit(0);
		} catch (Exception e) {
			System.out.println(e.getMessage());
			System.exit(1);
		}
	}
}
