/**
 * SchemaType.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package pack.model.altova.xml.types;

import java.io.Serializable;

@SuppressWarnings("unchecked")
public interface SchemaType extends Cloneable, Comparable, Serializable {
	public String toString();
	public String asString();
}
