/**
 * SchemaShort.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package pack.model.altova.xml.types;

class SchemaShort implements SchemaType {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private short value;

	private SchemaShort(int newvalue) {
		value = (short)newvalue;
	}

	public int hashCode() {
		return value;
	}

	public boolean equals(Object obj) {
		if (!(obj instanceof SchemaShort))
			return false;
		return value == ((SchemaShort)obj).value;
	}

	public Object clone() {
		return new SchemaShort(value);
	}

	public String toString() {
		return Short.toString(value);
	}

	public String asString() {
		return toString();
	}

	public int compareTo(Object obj) {
		return compareTo((SchemaShort)obj);
	}

	private int compareTo(SchemaShort obj) {
		return new Short(value).compareTo(new Short(obj.value));
	}
}
