/**
 * SchemaID.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package pack.model.altova.xml.types;

public class SchemaID extends SchemaNCName {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public SchemaID(String newvalue) {
		super(newvalue);
	}
}
