/**
 * SchemaBoolean.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package pack.model.altova.xml.types;

class SchemaBoolean implements SchemaType {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private boolean value;

	private SchemaBoolean(boolean newvalue) {
		value = newvalue;
	}

	public int hashCode() {
		return value ? 1231 : 1237;
	}

	public boolean equals(Object obj) {
		if (!(obj instanceof SchemaBoolean))
			return false;
		return value == ((SchemaBoolean)obj).value;
	}

	public Object clone() {
		return new SchemaBoolean(value);
	}

	public String toString() {
		return value ? "true" : "false";
	}

	public String asString() {
		return toString();
	}

	public int compareTo(Object obj) {
		return compareTo((SchemaBoolean)obj);
	}

	private int compareTo(SchemaBoolean obj) {
		if (value == obj.value)
			return 0;
		else if (value == false)
			return -1;
		else
			return 1;
	}
}
