/**
 * nonNegativeFloat.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.schema;

import com.altova.xml.types.SchemaFloat;

public class nonNegativeFloat extends SchemaFloat {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public nonNegativeFloat(String newValue) {
		super(newValue);
		validate();
	}

	private void validate() {

		if (compareTo(getMinInclusive()) < 0)
			throw new com.altova.xml.XmlException("Out of range");
	}
	private SchemaFloat getMinInclusive() {
		return new SchemaFloat("0.0");
	}
}
