/**
 * Document.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.schema;

public class pmifschemaDoc extends com.altova.xml.Document {

	private static final long serialVersionUID = 1L;

	public void declareNamespaces(com.altova.xml.Node node) {
	}
}
