/**
 * SchedulingType.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.schema;

import com.altova.xml.types.SchemaString;

/**
 * Indica la disciplina di servizio usata per selezionare,
 * dalla coda di attesa, la prossima richiesta di servizio
 * (ServiceRequest) che deve essere servita.
 * <pre>
 * <code>
 * &lt;xsd:simpleType name="SchedulingType"&gt;
 * 	&lt;xsd:restriction base="xsd:string"&gt;
 * 		&lt;!--
 * 		Il primo ad entrare nella coda viene servito per
 * 		primo.
 * 		--&gt;
 * 		&lt;xsd:enumeration value="FCFS"/&gt;
 * 		&lt;!-- infiniti servers --&gt;
 * 		&lt;xsd:enumeration value="IS"/&gt;
 * 		&lt;!--
 * 		condivisione del processore (Processor Sharing).
 * 		Quando nel centro di servizio sono presenti q utenti,
 * 		ognuno riceve servizio con velocità pari ad (1/q) del
 * 		tasso di servizio.
 * 		--&gt;
 * 		&lt;xsd:enumeration value="PS"/&gt;
 * 	&lt;/xsd:restriction&gt;
 * &lt;/xsd:simpleType&gt;
 * </code>
 * </pre>
 *
 * @author Mirko Email: <a href="mailto:mirkoflamminj@virgilio.it">mirkoflamminj@virgilio.it</a>
 * @version 1.0
 */
public class SchedulingType extends SchemaString {
	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	public SchedulingType(String newValue) {
		super(newValue);
		validate();
	}

	public void validate() {
	}
}
