/**
 * TimeUnitsType.java
 *
 * This file was generated by XMLSPY 5 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.schema;

import com.altova.xml.types.SchemaString;

/**
 * Ove presente, TimeUnits indica l'unità di tempo usata per
 * specificare una quantità temporale. Se viene omessa, tutte
 * le quantità riferibili al trascorrere del tempo vengono
 * assunte come avere la stessa unità di tempo.
 * Le specifiche PMIF 2.0 sono poco chiare relativamente
 * all'attributo TimeUnits, in quanto essendo opzionale in
 * tutti gli elementi che compongono un file PMIF, non �
 * chiaro come comportarsi nel caso in cui venga specificato
 * in quasi tutti gli elementi con unità di tempo differenti
 * (ore, minuti, secondi, ecc) tranne in uno. Nel caso sia
 * assente in un solo elemento ma presente in tutti gli
 * altri, la strategia di importazione dovrebbe decidere di
 * convertire tutti i tempi in un'unica unità, ma quale? Ore?
 * Minuti? o Secondi?
 * <pre>
 * <code>
 * &lt;xsd:simpleType name="TimeUnitsType"&gt;
 * 	&lt;xsd:annotation&gt;
 * 		&lt;xsd:documentation&gt;
 * 			If time units are omitted, all specifications are assumed to be the same relative units.
 * 		&lt;/xsd:documentation&gt;
 * 	&lt;/xsd:annotation&gt;
 * 	&lt;xsd:restriction base="xsd:string"&gt;
 * 		&lt;xsd:enumeration value="day"/&gt;
 * 		&lt;xsd:enumeration value="Day"/&gt;
 * 		&lt;xsd:enumeration value="hr"/&gt;
 * 		&lt;xsd:enumeration value="Hr"/&gt;
 * 		&lt;xsd:enumeration value="min"/&gt;
 * 		&lt;xsd:enumeration value="Min"/&gt;
 * 		&lt;xsd:enumeration value="sec"/&gt;
 * 		&lt;xsd:enumeration value="Sec"/&gt;
 * 		&lt;xsd:enumeration value="ms"/&gt;
 * 		&lt;xsd:enumeration value="Ms"/&gt;
 * 		&lt;xsd:enumeration value="ns"/&gt;
 * 		&lt;xsd:enumeration value="Ns"/&gt;
 * 	&lt;/xsd:restriction&gt;
 * &lt;/xsd:simpleType&gt;
 * </code>
 * </pre>
 *
 * @author Mirko Email: <a href="mailto:mirkoflamminj@virgilio.it">mirkoflamminj@virgilio.it</a>
 * @version 1.0
 */
public class TimeUnitsType extends SchemaString {

	private static final long serialVersionUID = 1L;

	public TimeUnitsType(String newValue) {
		super(newValue);
		validate();
	}

	public void validate() {
	}
}
